/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssignmentType = IDL.Variant({
  'user' : IDL.Principal,
  'department' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const EscalationRule = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'taskType' : IDL.Text,
  'thresholdMinutes' : IDL.Nat,
});
export const ValidationRules = IDL.Record({
  'minValue' : IDL.Opt(IDL.Int),
  'required' : IDL.Bool,
  'maxLength' : IDL.Opt(IDL.Nat),
  'maxValue' : IDL.Opt(IDL.Int),
  'minLength' : IDL.Opt(IDL.Nat),
});
export const FormFieldOption = IDL.Record({
  'value' : IDL.Text,
  'fieldLabel' : IDL.Text,
});
export const FieldType = IDL.Variant({
  'date' : IDL.Null,
  'multiSelect' : IDL.Null,
  'fileUpload' : IDL.Null,
  'multiLine' : IDL.Null,
  'number' : IDL.Null,
  'singleLine' : IDL.Null,
  'dateTime' : IDL.Null,
  'dropdown' : IDL.Null,
});
export const FormField = IDL.Record({
  'id' : IDL.Text,
  'masterListRef' : IDL.Opt(IDL.Text),
  'fieldLabel' : IDL.Text,
  'validations' : IDL.Opt(ValidationRules),
  'options' : IDL.Opt(IDL.Vec(FormFieldOption)),
  'fieldType' : FieldType,
});
export const FormDefinition = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'version' : IDL.Nat,
  'fields' : IDL.Vec(FormField),
});
export const MasterListItem = IDL.Record({
  'value' : IDL.Text,
  'itemLabel' : IDL.Text,
});
export const MasterList = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'items' : IDL.Vec(MasterListItem),
});
export const Priority = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const Status = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const TaskFormAttachment = IDL.Record({
  'completed' : IDL.Bool,
  'formDefinitionId' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'completionDate' : IDL.Opt(IDL.Int),
  'assignment' : IDL.Opt(AssignmentType),
  'owner' : IDL.Principal,
  'attachedForms' : IDL.Vec(TaskFormAttachment),
  'createdDate' : IDL.Int,
  'dueDate' : IDL.Int,
  'taskType' : IDL.Text,
  'priority' : IDL.Text,
});
export const TaskType = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FieldValue = IDL.Variant({
  'date' : IDL.Int,
  'file' : ExternalBlob,
  'text' : IDL.Text,
  'singleChoice' : IDL.Text,
  'number' : IDL.Int,
  'multipleChoices' : IDL.Vec(IDL.Text),
  'dateTime' : IDL.Int,
});
export const FormFieldInput = IDL.Record({
  'value' : FieldValue,
  'fieldId' : IDL.Text,
});
export const DynamicFormInput = IDL.Record({
  'data' : IDL.Vec(FormFieldInput),
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'version' : IDL.Nat,
  'formId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const TaskAction = IDL.Variant({
  'assigned' : IDL.Null,
  'created' : IDL.Null,
  'escalated' : IDL.Null,
  'completed' : IDL.Null,
  'formSubmitted' : IDL.Null,
  'pickedUp' : IDL.Null,
  'statusChanged' : IDL.Null,
  'reassigned' : IDL.Null,
});
export const TaskAuditEntry = IDL.Record({
  'action' : TaskAction,
  'user' : IDL.Principal,
  'taskId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTask' : IDL.Func([IDL.Text, AssignmentType], [], []),
  'createCategory' : IDL.Func([Category], [], []),
  'createDepartment' : IDL.Func([Department], [], []),
  'createEscalationRule' : IDL.Func([EscalationRule], [], []),
  'createFormDefinition' : IDL.Func([FormDefinition], [], []),
  'createMasterList' : IDL.Func([MasterList], [], []),
  'createPriority' : IDL.Func([Priority], [], []),
  'createStatus' : IDL.Func([Status], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'createTaskType' : IDL.Func([TaskType], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteDepartment' : IDL.Func([IDL.Text], [], []),
  'deleteEscalationRule' : IDL.Func([IDL.Text], [], []),
  'deleteFormDefinition' : IDL.Func([IDL.Text], [], []),
  'deleteMasterList' : IDL.Func([IDL.Text], [], []),
  'deletePriority' : IDL.Func([IDL.Text], [], []),
  'deleteStatus' : IDL.Func([IDL.Text], [], []),
  'deleteTaskType' : IDL.Func([IDL.Text], [], []),
  'getAllFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(DynamicFormInput)],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getDepartment' : IDL.Func([IDL.Text], [IDL.Opt(Department)], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getEscalationRule' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EscalationRule)],
      ['query'],
    ),
  'getEscalationRules' : IDL.Func([], [IDL.Vec(EscalationRule)], ['query']),
  'getFormDefinition' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FormDefinition)],
      ['query'],
    ),
  'getFormDefinitions' : IDL.Func([], [IDL.Vec(FormDefinition)], ['query']),
  'getFormSubmission' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DynamicFormInput)],
      ['query'],
    ),
  'getMasterList' : IDL.Func([IDL.Text], [IDL.Opt(MasterList)], ['query']),
  'getMasterLists' : IDL.Func([], [IDL.Vec(MasterList)], ['query']),
  'getMyFormSubmissions' : IDL.Func([], [IDL.Vec(DynamicFormInput)], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getPriorities' : IDL.Func([], [IDL.Vec(Priority)], ['query']),
  'getPriority' : IDL.Func([IDL.Text], [IDL.Opt(Priority)], ['query']),
  'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], ['query']),
  'getStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getTaskAuditLog' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TaskAuditEntry)],
      ['query'],
    ),
  'getTaskType' : IDL.Func([IDL.Text], [IDL.Opt(TaskType)], ['query']),
  'getTaskTypes' : IDL.Func([], [IDL.Vec(TaskType)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitForm' : IDL.Func([DynamicFormInput], [IDL.Text], []),
  'submitTaskForm' : IDL.Func([IDL.Text, DynamicFormInput], [], []),
  'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
  'updateDepartment' : IDL.Func([IDL.Text, Department], [], []),
  'updateEscalationRule' : IDL.Func([IDL.Text, EscalationRule], [], []),
  'updateFormDefinition' : IDL.Func([IDL.Text, FormDefinition], [], []),
  'updateMasterList' : IDL.Func([IDL.Text, MasterList], [], []),
  'updatePriority' : IDL.Func([IDL.Text, Priority], [], []),
  'updateStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateTask' : IDL.Func([IDL.Text, Task], [], []),
  'updateTaskType' : IDL.Func([IDL.Text, TaskType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssignmentType = IDL.Variant({
    'user' : IDL.Principal,
    'department' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const EscalationRule = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'taskType' : IDL.Text,
    'thresholdMinutes' : IDL.Nat,
  });
  const ValidationRules = IDL.Record({
    'minValue' : IDL.Opt(IDL.Int),
    'required' : IDL.Bool,
    'maxLength' : IDL.Opt(IDL.Nat),
    'maxValue' : IDL.Opt(IDL.Int),
    'minLength' : IDL.Opt(IDL.Nat),
  });
  const FormFieldOption = IDL.Record({
    'value' : IDL.Text,
    'fieldLabel' : IDL.Text,
  });
  const FieldType = IDL.Variant({
    'date' : IDL.Null,
    'multiSelect' : IDL.Null,
    'fileUpload' : IDL.Null,
    'multiLine' : IDL.Null,
    'number' : IDL.Null,
    'singleLine' : IDL.Null,
    'dateTime' : IDL.Null,
    'dropdown' : IDL.Null,
  });
  const FormField = IDL.Record({
    'id' : IDL.Text,
    'masterListRef' : IDL.Opt(IDL.Text),
    'fieldLabel' : IDL.Text,
    'validations' : IDL.Opt(ValidationRules),
    'options' : IDL.Opt(IDL.Vec(FormFieldOption)),
    'fieldType' : FieldType,
  });
  const FormDefinition = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'version' : IDL.Nat,
    'fields' : IDL.Vec(FormField),
  });
  const MasterListItem = IDL.Record({
    'value' : IDL.Text,
    'itemLabel' : IDL.Text,
  });
  const MasterList = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'items' : IDL.Vec(MasterListItem),
  });
  const Priority = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const Status = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const TaskFormAttachment = IDL.Record({
    'completed' : IDL.Bool,
    'formDefinitionId' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'completionDate' : IDL.Opt(IDL.Int),
    'assignment' : IDL.Opt(AssignmentType),
    'owner' : IDL.Principal,
    'attachedForms' : IDL.Vec(TaskFormAttachment),
    'createdDate' : IDL.Int,
    'dueDate' : IDL.Int,
    'taskType' : IDL.Text,
    'priority' : IDL.Text,
  });
  const TaskType = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FieldValue = IDL.Variant({
    'date' : IDL.Int,
    'file' : ExternalBlob,
    'text' : IDL.Text,
    'singleChoice' : IDL.Text,
    'number' : IDL.Int,
    'multipleChoices' : IDL.Vec(IDL.Text),
    'dateTime' : IDL.Int,
  });
  const FormFieldInput = IDL.Record({
    'value' : FieldValue,
    'fieldId' : IDL.Text,
  });
  const DynamicFormInput = IDL.Record({
    'data' : IDL.Vec(FormFieldInput),
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'version' : IDL.Nat,
    'formId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const TaskAction = IDL.Variant({
    'assigned' : IDL.Null,
    'created' : IDL.Null,
    'escalated' : IDL.Null,
    'completed' : IDL.Null,
    'formSubmitted' : IDL.Null,
    'pickedUp' : IDL.Null,
    'statusChanged' : IDL.Null,
    'reassigned' : IDL.Null,
  });
  const TaskAuditEntry = IDL.Record({
    'action' : TaskAction,
    'user' : IDL.Principal,
    'taskId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTask' : IDL.Func([IDL.Text, AssignmentType], [], []),
    'createCategory' : IDL.Func([Category], [], []),
    'createDepartment' : IDL.Func([Department], [], []),
    'createEscalationRule' : IDL.Func([EscalationRule], [], []),
    'createFormDefinition' : IDL.Func([FormDefinition], [], []),
    'createMasterList' : IDL.Func([MasterList], [], []),
    'createPriority' : IDL.Func([Priority], [], []),
    'createStatus' : IDL.Func([Status], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'createTaskType' : IDL.Func([TaskType], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteDepartment' : IDL.Func([IDL.Text], [], []),
    'deleteEscalationRule' : IDL.Func([IDL.Text], [], []),
    'deleteFormDefinition' : IDL.Func([IDL.Text], [], []),
    'deleteMasterList' : IDL.Func([IDL.Text], [], []),
    'deletePriority' : IDL.Func([IDL.Text], [], []),
    'deleteStatus' : IDL.Func([IDL.Text], [], []),
    'deleteTaskType' : IDL.Func([IDL.Text], [], []),
    'getAllFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(DynamicFormInput)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAssignedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getDepartment' : IDL.Func([IDL.Text], [IDL.Opt(Department)], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getEscalationRule' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EscalationRule)],
        ['query'],
      ),
    'getEscalationRules' : IDL.Func([], [IDL.Vec(EscalationRule)], ['query']),
    'getFormDefinition' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FormDefinition)],
        ['query'],
      ),
    'getFormDefinitions' : IDL.Func([], [IDL.Vec(FormDefinition)], ['query']),
    'getFormSubmission' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DynamicFormInput)],
        ['query'],
      ),
    'getMasterList' : IDL.Func([IDL.Text], [IDL.Opt(MasterList)], ['query']),
    'getMasterLists' : IDL.Func([], [IDL.Vec(MasterList)], ['query']),
    'getMyFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(DynamicFormInput)],
        ['query'],
      ),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getPriorities' : IDL.Func([], [IDL.Vec(Priority)], ['query']),
    'getPriority' : IDL.Func([IDL.Text], [IDL.Opt(Priority)], ['query']),
    'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], ['query']),
    'getStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getTaskAuditLog' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TaskAuditEntry)],
        ['query'],
      ),
    'getTaskType' : IDL.Func([IDL.Text], [IDL.Opt(TaskType)], ['query']),
    'getTaskTypes' : IDL.Func([], [IDL.Vec(TaskType)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitForm' : IDL.Func([DynamicFormInput], [IDL.Text], []),
    'submitTaskForm' : IDL.Func([IDL.Text, DynamicFormInput], [], []),
    'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
    'updateDepartment' : IDL.Func([IDL.Text, Department], [], []),
    'updateEscalationRule' : IDL.Func([IDL.Text, EscalationRule], [], []),
    'updateFormDefinition' : IDL.Func([IDL.Text, FormDefinition], [], []),
    'updateMasterList' : IDL.Func([IDL.Text, MasterList], [], []),
    'updatePriority' : IDL.Func([IDL.Text, Priority], [], []),
    'updateStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateTask' : IDL.Func([IDL.Text, Task], [], []),
    'updateTaskType' : IDL.Func([IDL.Text, TaskType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };