/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
}
export interface Department {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
}
export interface EscalationRule {
  'id' : string,
  'action' : string,
  'taskType' : string,
  'thresholdMinutes' : bigint,
}
export type FieldType = { 'date' : null } |
  { 'multiSelect' : null } |
  { 'fileUpload' : null } |
  { 'multiLine' : null } |
  { 'number' : null } |
  { 'singleLine' : null } |
  { 'dateTime' : null } |
  { 'dropdown' : null };
export interface FormDefinition {
  'id' : string,
  'created' : bigint,
  'creator' : Principal,
  'name' : string,
  'lastUpdated' : bigint,
  'version' : bigint,
  'fields' : Array<FormField>,
}
export interface FormField {
  'id' : string,
  'masterListRef' : [] | [string],
  'fieldLabel' : string,
  'validations' : [] | [ValidationRules],
  'options' : [] | [Array<FormFieldOption>],
  'fieldType' : FieldType,
}
export interface FormFieldOption { 'value' : string, 'fieldLabel' : string }
export interface MasterList {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
  'items' : Array<MasterListItem>,
}
export interface MasterListItem { 'value' : string, 'itemLabel' : string }
export interface Priority {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
}
export interface Status {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
}
export interface TaskType {
  'id' : string,
  'created' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidationRules {
  'minValue' : [] | [bigint],
  'required' : boolean,
  'maxLength' : [] | [bigint],
  'maxValue' : [] | [bigint],
  'minLength' : [] | [bigint],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createDepartment' : ActorMethod<[Department], undefined>,
  'createEscalationRule' : ActorMethod<[EscalationRule], undefined>,
  'createFormDefinition' : ActorMethod<[FormDefinition], undefined>,
  'createMasterList' : ActorMethod<[MasterList], undefined>,
  'createPriority' : ActorMethod<[Priority], undefined>,
  'createStatus' : ActorMethod<[Status], undefined>,
  'createTaskType' : ActorMethod<[TaskType], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteDepartment' : ActorMethod<[string], undefined>,
  'deleteEscalationRule' : ActorMethod<[string], undefined>,
  'deleteFormDefinition' : ActorMethod<[string], undefined>,
  'deleteMasterList' : ActorMethod<[string], undefined>,
  'deletePriority' : ActorMethod<[string], undefined>,
  'deleteStatus' : ActorMethod<[string], undefined>,
  'deleteTaskType' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[string, Category], undefined>,
  'updateDepartment' : ActorMethod<[string, Department], undefined>,
  'updateEscalationRule' : ActorMethod<[string, EscalationRule], undefined>,
  'updateFormDefinition' : ActorMethod<[string, FormDefinition], undefined>,
  'updateMasterList' : ActorMethod<[string, MasterList], undefined>,
  'updatePriority' : ActorMethod<[string, Priority], undefined>,
  'updateStatus' : ActorMethod<[string, Status], undefined>,
  'updateTaskType' : ActorMethod<[string, TaskType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];