/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const EscalationRule = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'taskType' : IDL.Text,
  'thresholdMinutes' : IDL.Nat,
});
export const ValidationRules = IDL.Record({
  'minValue' : IDL.Opt(IDL.Int),
  'required' : IDL.Bool,
  'maxLength' : IDL.Opt(IDL.Nat),
  'maxValue' : IDL.Opt(IDL.Int),
  'minLength' : IDL.Opt(IDL.Nat),
});
export const FormFieldOption = IDL.Record({
  'value' : IDL.Text,
  'fieldLabel' : IDL.Text,
});
export const FieldType = IDL.Variant({
  'date' : IDL.Null,
  'multiSelect' : IDL.Null,
  'fileUpload' : IDL.Null,
  'multiLine' : IDL.Null,
  'number' : IDL.Null,
  'singleLine' : IDL.Null,
  'dateTime' : IDL.Null,
  'dropdown' : IDL.Null,
});
export const FormField = IDL.Record({
  'id' : IDL.Text,
  'masterListRef' : IDL.Opt(IDL.Text),
  'fieldLabel' : IDL.Text,
  'validations' : IDL.Opt(ValidationRules),
  'options' : IDL.Opt(IDL.Vec(FormFieldOption)),
  'fieldType' : FieldType,
});
export const FormDefinition = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'version' : IDL.Nat,
  'fields' : IDL.Vec(FormField),
});
export const MasterListItem = IDL.Record({
  'value' : IDL.Text,
  'itemLabel' : IDL.Text,
});
export const MasterList = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'items' : IDL.Vec(MasterListItem),
});
export const Priority = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const Status = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const TaskType = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([Category], [], []),
  'createDepartment' : IDL.Func([Department], [], []),
  'createEscalationRule' : IDL.Func([EscalationRule], [], []),
  'createFormDefinition' : IDL.Func([FormDefinition], [], []),
  'createMasterList' : IDL.Func([MasterList], [], []),
  'createPriority' : IDL.Func([Priority], [], []),
  'createStatus' : IDL.Func([Status], [], []),
  'createTaskType' : IDL.Func([TaskType], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteDepartment' : IDL.Func([IDL.Text], [], []),
  'deleteEscalationRule' : IDL.Func([IDL.Text], [], []),
  'deleteFormDefinition' : IDL.Func([IDL.Text], [], []),
  'deleteMasterList' : IDL.Func([IDL.Text], [], []),
  'deletePriority' : IDL.Func([IDL.Text], [], []),
  'deleteStatus' : IDL.Func([IDL.Text], [], []),
  'deleteTaskType' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
  'updateDepartment' : IDL.Func([IDL.Text, Department], [], []),
  'updateEscalationRule' : IDL.Func([IDL.Text, EscalationRule], [], []),
  'updateFormDefinition' : IDL.Func([IDL.Text, FormDefinition], [], []),
  'updateMasterList' : IDL.Func([IDL.Text, MasterList], [], []),
  'updatePriority' : IDL.Func([IDL.Text, Priority], [], []),
  'updateStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateTaskType' : IDL.Func([IDL.Text, TaskType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const EscalationRule = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'taskType' : IDL.Text,
    'thresholdMinutes' : IDL.Nat,
  });
  const ValidationRules = IDL.Record({
    'minValue' : IDL.Opt(IDL.Int),
    'required' : IDL.Bool,
    'maxLength' : IDL.Opt(IDL.Nat),
    'maxValue' : IDL.Opt(IDL.Int),
    'minLength' : IDL.Opt(IDL.Nat),
  });
  const FormFieldOption = IDL.Record({
    'value' : IDL.Text,
    'fieldLabel' : IDL.Text,
  });
  const FieldType = IDL.Variant({
    'date' : IDL.Null,
    'multiSelect' : IDL.Null,
    'fileUpload' : IDL.Null,
    'multiLine' : IDL.Null,
    'number' : IDL.Null,
    'singleLine' : IDL.Null,
    'dateTime' : IDL.Null,
    'dropdown' : IDL.Null,
  });
  const FormField = IDL.Record({
    'id' : IDL.Text,
    'masterListRef' : IDL.Opt(IDL.Text),
    'fieldLabel' : IDL.Text,
    'validations' : IDL.Opt(ValidationRules),
    'options' : IDL.Opt(IDL.Vec(FormFieldOption)),
    'fieldType' : FieldType,
  });
  const FormDefinition = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'version' : IDL.Nat,
    'fields' : IDL.Vec(FormField),
  });
  const MasterListItem = IDL.Record({
    'value' : IDL.Text,
    'itemLabel' : IDL.Text,
  });
  const MasterList = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'items' : IDL.Vec(MasterListItem),
  });
  const Priority = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const Status = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const TaskType = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([Category], [], []),
    'createDepartment' : IDL.Func([Department], [], []),
    'createEscalationRule' : IDL.Func([EscalationRule], [], []),
    'createFormDefinition' : IDL.Func([FormDefinition], [], []),
    'createMasterList' : IDL.Func([MasterList], [], []),
    'createPriority' : IDL.Func([Priority], [], []),
    'createStatus' : IDL.Func([Status], [], []),
    'createTaskType' : IDL.Func([TaskType], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteDepartment' : IDL.Func([IDL.Text], [], []),
    'deleteEscalationRule' : IDL.Func([IDL.Text], [], []),
    'deleteFormDefinition' : IDL.Func([IDL.Text], [], []),
    'deleteMasterList' : IDL.Func([IDL.Text], [], []),
    'deletePriority' : IDL.Func([IDL.Text], [], []),
    'deleteStatus' : IDL.Func([IDL.Text], [], []),
    'deleteTaskType' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
    'updateDepartment' : IDL.Func([IDL.Text, Department], [], []),
    'updateEscalationRule' : IDL.Func([IDL.Text, EscalationRule], [], []),
    'updateFormDefinition' : IDL.Func([IDL.Text, FormDefinition], [], []),
    'updateMasterList' : IDL.Func([IDL.Text, MasterList], [], []),
    'updatePriority' : IDL.Func([IDL.Text, Priority], [], []),
    'updateStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateTaskType' : IDL.Func([IDL.Text, TaskType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };