/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FormFieldInput {
    value: FieldValue;
    fieldId: string;
}
export interface Category {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
}
export interface Priority {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
}
export interface FormField {
    id: string;
    masterListRef?: string;
    fieldLabel: string;
    validations?: ValidationRules;
    options?: Array<FormFieldOption>;
    fieldType: FieldType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type FieldValue = {
    __kind__: "date";
    date: bigint;
} | {
    __kind__: "file";
    file: ExternalBlob;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "singleChoice";
    singleChoice: string;
} | {
    __kind__: "number";
    number: bigint;
} | {
    __kind__: "multipleChoices";
    multipleChoices: Array<string>;
} | {
    __kind__: "dateTime";
    dateTime: bigint;
};
export interface Task {
    id: string;
    status: string;
    completionDate?: bigint;
    assignment?: AssignmentType;
    owner: Principal;
    attachedForms: Array<TaskFormAttachment>;
    createdDate: bigint;
    dueDate: bigint;
    taskType: string;
    priority: string;
}
export interface MasterListItem {
    value: string;
    itemLabel: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TaskAuditEntry {
    action: TaskAction;
    user: Principal;
    taskId: string;
    timestamp: bigint;
    details: string;
}
export interface TaskFormAttachment {
    completed: boolean;
    formDefinitionId: string;
}
export interface TaskType {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
}
export interface ValidationRules {
    minValue?: bigint;
    required: boolean;
    maxLength?: bigint;
    maxValue?: bigint;
    minLength?: bigint;
}
export interface MasterList {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
    items: Array<MasterListItem>;
}
export interface DynamicFormInput {
    data: Array<FormFieldInput>;
    submittedAt: bigint;
    submittedBy: Principal;
    version: bigint;
    formId: string;
}
export interface Department {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
}
export type AssignmentType = {
    __kind__: "user";
    user: Principal;
} | {
    __kind__: "department";
    department: string;
};
export interface FormFieldOption {
    value: string;
    fieldLabel: string;
}
export interface FormDefinition {
    id: string;
    created: bigint;
    creator: Principal;
    name: string;
    lastUpdated: bigint;
    version: bigint;
    fields: Array<FormField>;
}
export interface Status {
    id: string;
    created: bigint;
    name: string;
    lastUpdated: bigint;
}
export interface EscalationRule {
    id: string;
    action: string;
    taskType: string;
    thresholdMinutes: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    department?: string;
}
export enum FieldType {
    date = "date",
    multiSelect = "multiSelect",
    fileUpload = "fileUpload",
    multiLine = "multiLine",
    number_ = "number",
    singleLine = "singleLine",
    dateTime = "dateTime",
    dropdown = "dropdown"
}
export enum TaskAction {
    assigned = "assigned",
    created = "created",
    escalated = "escalated",
    completed = "completed",
    formSubmitted = "formSubmitted",
    pickedUp = "pickedUp",
    statusChanged = "statusChanged",
    reassigned = "reassigned"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTask(taskId: string, assignment: AssignmentType): Promise<void>;
    createCategory(category: Category): Promise<void>;
    createDepartment(department: Department): Promise<void>;
    createEscalationRule(rule: EscalationRule): Promise<void>;
    createFormDefinition(formDefinition: FormDefinition): Promise<void>;
    createMasterList(masterList: MasterList): Promise<void>;
    createPriority(priority: Priority): Promise<void>;
    createStatus(status: Status): Promise<void>;
    createTask(task: Task): Promise<void>;
    createTaskType(taskType: TaskType): Promise<void>;
    deleteCategory(id: string): Promise<void>;
    deleteDepartment(id: string): Promise<void>;
    deleteEscalationRule(id: string): Promise<void>;
    deleteFormDefinition(id: string): Promise<void>;
    deleteMasterList(id: string): Promise<void>;
    deletePriority(id: string): Promise<void>;
    deleteStatus(id: string): Promise<void>;
    deleteTaskType(id: string): Promise<void>;
    getAllFormSubmissions(): Promise<Array<DynamicFormInput>>;
    getAllTasks(): Promise<Array<Task>>;
    getAssignedTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getCategory(id: string): Promise<Category | null>;
    getDepartment(id: string): Promise<Department | null>;
    getDepartments(): Promise<Array<Department>>;
    getEscalationRule(id: string): Promise<EscalationRule | null>;
    getEscalationRules(): Promise<Array<EscalationRule>>;
    getFormDefinition(id: string): Promise<FormDefinition | null>;
    getFormDefinitions(): Promise<Array<FormDefinition>>;
    getFormSubmission(submissionId: string): Promise<DynamicFormInput | null>;
    getMasterList(id: string): Promise<MasterList | null>;
    getMasterLists(): Promise<Array<MasterList>>;
    getMyFormSubmissions(): Promise<Array<DynamicFormInput>>;
    getMyTasks(): Promise<Array<Task>>;
    getPriorities(): Promise<Array<Priority>>;
    getPriority(id: string): Promise<Priority | null>;
    getStatus(id: string): Promise<Status | null>;
    getStatuses(): Promise<Array<Status>>;
    getTask(id: string): Promise<Task | null>;
    getTaskAuditLog(taskId: string): Promise<Array<TaskAuditEntry>>;
    getTaskType(id: string): Promise<TaskType | null>;
    getTaskTypes(): Promise<Array<TaskType>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitForm(submission: DynamicFormInput): Promise<string>;
    submitTaskForm(taskId: string, formSubmission: DynamicFormInput): Promise<void>;
    updateCategory(id: string, category: Category): Promise<void>;
    updateDepartment(id: string, department: Department): Promise<void>;
    updateEscalationRule(id: string, rule: EscalationRule): Promise<void>;
    updateFormDefinition(id: string, formDefinition: FormDefinition): Promise<void>;
    updateMasterList(id: string, masterList: MasterList): Promise<void>;
    updatePriority(id: string, priority: Priority): Promise<void>;
    updateStatus(id: string, status: Status): Promise<void>;
    updateTask(id: string, task: Task): Promise<void>;
    updateTaskType(id: string, taskType: TaskType): Promise<void>;
}
import type { AssignmentType as _AssignmentType, Category as _Category, Department as _Department, DynamicFormInput as _DynamicFormInput, EscalationRule as _EscalationRule, ExternalBlob as _ExternalBlob, FieldType as _FieldType, FieldValue as _FieldValue, FormDefinition as _FormDefinition, FormField as _FormField, FormFieldInput as _FormFieldInput, FormFieldOption as _FormFieldOption, MasterList as _MasterList, Priority as _Priority, Status as _Status, Task as _Task, TaskAction as _TaskAction, TaskAuditEntry as _TaskAuditEntry, TaskFormAttachment as _TaskFormAttachment, TaskType as _TaskType, UserProfile as _UserProfile, UserRole as _UserRole, ValidationRules as _ValidationRules, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTask(arg0: string, arg1: AssignmentType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTask(arg0, to_candid_AssignmentType_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTask(arg0, to_candid_AssignmentType_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createDepartment(arg0: Department): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepartment(arg0);
            return result;
        }
    }
    async createEscalationRule(arg0: EscalationRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEscalationRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEscalationRule(arg0);
            return result;
        }
    }
    async createFormDefinition(arg0: FormDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFormDefinition(to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFormDefinition(to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMasterList(arg0: MasterList): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMasterList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMasterList(arg0);
            return result;
        }
    }
    async createPriority(arg0: Priority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPriority(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPriority(arg0);
            return result;
        }
    }
    async createStatus(arg0: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStatus(arg0);
            return result;
        }
    }
    async createTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTaskType(arg0: TaskType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTaskType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTaskType(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteDepartment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDepartment(arg0);
            return result;
        }
    }
    async deleteEscalationRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEscalationRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEscalationRule(arg0);
            return result;
        }
    }
    async deleteFormDefinition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFormDefinition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFormDefinition(arg0);
            return result;
        }
    }
    async deleteMasterList(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMasterList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMasterList(arg0);
            return result;
        }
    }
    async deletePriority(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePriority(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePriority(arg0);
            return result;
        }
    }
    async deleteStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStatus(arg0);
            return result;
        }
    }
    async deleteTaskType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTaskType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTaskType(arg0);
            return result;
        }
    }
    async getAllFormSubmissions(): Promise<Array<DynamicFormInput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFormSubmissions();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFormSubmissions();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedTasks();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedTasks();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartment(arg0: string): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartments();
            return result;
        }
    }
    async getEscalationRule(arg0: string): Promise<EscalationRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEscalationRule(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEscalationRule(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEscalationRules(): Promise<Array<EscalationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEscalationRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEscalationRules();
            return result;
        }
    }
    async getFormDefinition(arg0: string): Promise<FormDefinition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormDefinition(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormDefinition(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFormDefinitions(): Promise<Array<FormDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormDefinitions();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormDefinitions();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFormSubmission(arg0: string): Promise<DynamicFormInput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormSubmission(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormSubmission(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterList(arg0: string): Promise<MasterList | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterList(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterList(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterLists(): Promise<Array<MasterList>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterLists();
            return result;
        }
    }
    async getMyFormSubmissions(): Promise<Array<DynamicFormInput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFormSubmissions();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFormSubmissions();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriorities(): Promise<Array<Priority>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriorities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriorities();
            return result;
        }
    }
    async getPriority(arg0: string): Promise<Priority | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriority(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriority(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatus(arg0: string): Promise<Status | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatuses(): Promise<Array<Status>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatuses();
            return result;
        }
    }
    async getTask(arg0: string): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskAuditLog(arg0: string): Promise<Array<TaskAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskAuditLog(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskAuditLog(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskType(arg0: string): Promise<TaskType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskType(arg0);
                return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskType(arg0);
            return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskTypes(): Promise<Array<TaskType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskTypes();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitForm(arg0: DynamicFormInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(await to_candid_DynamicFormInput_n74(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(await to_candid_DynamicFormInput_n74(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTaskForm(arg0: string, arg1: DynamicFormInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTaskForm(arg0, await to_candid_DynamicFormInput_n74(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTaskForm(arg0, await to_candid_DynamicFormInput_n74(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateDepartment(arg0: string, arg1: Department): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDepartment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDepartment(arg0, arg1);
            return result;
        }
    }
    async updateEscalationRule(arg0: string, arg1: EscalationRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEscalationRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEscalationRule(arg0, arg1);
            return result;
        }
    }
    async updateFormDefinition(arg0: string, arg1: FormDefinition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFormDefinition(arg0, to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFormDefinition(arg0, to_candid_FormDefinition_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMasterList(arg0: string, arg1: MasterList): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMasterList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMasterList(arg0, arg1);
            return result;
        }
    }
    async updatePriority(arg0: string, arg1: Priority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePriority(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePriority(arg0, arg1);
            return result;
        }
    }
    async updateStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: string, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskType(arg0: string, arg1: TaskType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskType(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AssignmentType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentType): AssignmentType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_DynamicFormInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DynamicFormInput): Promise<DynamicFormInput> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FieldType_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldType): FieldType {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function from_candid_FieldValue_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldValue): Promise<FieldValue> {
    return await from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_FormDefinition_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormDefinition): FormDefinition {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_FormFieldInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormFieldInput): Promise<FormFieldInput> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_FormField_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormField): FormField {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TaskAction_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskAction): TaskAction {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_TaskAuditEntry_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskAuditEntry): TaskAuditEntry {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationRules_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationRules): ValidationRules {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssignmentType]): AssignmentType | null {
    return value.length === 0 ? null : from_candid_AssignmentType_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EscalationRule]): EscalationRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FormDefinition]): FormDefinition | null {
    return value.length === 0 ? null : from_candid_FormDefinition_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ValidationRules]): ValidationRules | null {
    return value.length === 0 ? null : from_candid_ValidationRules_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_FormFieldOption>]): Array<FormFieldOption> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DynamicFormInput]): Promise<DynamicFormInput | null> {
    return value.length === 0 ? null : await from_candid_DynamicFormInput_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MasterList]): MasterList | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Priority]): Priority | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Status]): Status | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskType]): TaskType | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    data: Array<_FormFieldInput>;
    submittedAt: bigint;
    submittedBy: Principal;
    version: bigint;
    formId: string;
}): Promise<{
    data: Array<FormFieldInput>;
    submittedAt: bigint;
    submittedBy: Principal;
    version: bigint;
    formId: string;
}> {
    return {
        data: await from_candid_vec_n26(_uploadFile, _downloadFile, value.data),
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        version: value.version,
        formId: value.formId
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _FieldValue;
    fieldId: string;
}): Promise<{
    value: FieldValue;
    fieldId: string;
}> {
    return {
        value: await from_candid_FieldValue_n29(_uploadFile, _downloadFile, value.value),
        fieldId: value.fieldId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    completionDate: [] | [bigint];
    assignment: [] | [_AssignmentType];
    owner: Principal;
    attachedForms: Array<_TaskFormAttachment>;
    createdDate: bigint;
    dueDate: bigint;
    taskType: string;
    priority: string;
}): {
    id: string;
    status: string;
    completionDate?: bigint;
    assignment?: AssignmentType;
    owner: Principal;
    attachedForms: Array<TaskFormAttachment>;
    createdDate: bigint;
    dueDate: bigint;
    taskType: string;
    priority: string;
} {
    return {
        id: value.id,
        status: value.status,
        completionDate: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.completionDate)),
        assignment: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.assignment)),
        owner: value.owner,
        attachedForms: value.attachedForms,
        createdDate: value.createdDate,
        dueDate: value.dueDate,
        taskType: value.taskType,
        priority: value.priority
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    department: [] | [string];
}): {
    name: string;
    email?: string;
    department?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.email)),
        department: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: bigint;
    creator: Principal;
    name: string;
    lastUpdated: bigint;
    version: bigint;
    fields: Array<_FormField>;
}): {
    id: string;
    created: bigint;
    creator: Principal;
    name: string;
    lastUpdated: bigint;
    version: bigint;
    fields: Array<FormField>;
} {
    return {
        id: value.id,
        created: value.created,
        creator: value.creator,
        name: value.name,
        lastUpdated: value.lastUpdated,
        version: value.version,
        fields: from_candid_vec_n51(_uploadFile, _downloadFile, value.fields)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    masterListRef: [] | [string];
    fieldLabel: string;
    validations: [] | [_ValidationRules];
    options: [] | [Array<_FormFieldOption>];
    fieldType: _FieldType;
}): {
    id: string;
    masterListRef?: string;
    fieldLabel: string;
    validations?: ValidationRules;
    options?: Array<FormFieldOption>;
    fieldType: FieldType;
} {
    return {
        id: value.id,
        masterListRef: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.masterListRef)),
        fieldLabel: value.fieldLabel,
        validations: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.validations)),
        options: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.options)),
        fieldType: from_candid_FieldType_n58(_uploadFile, _downloadFile, value.fieldType)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minValue: [] | [bigint];
    required: boolean;
    maxLength: [] | [bigint];
    maxValue: [] | [bigint];
    minLength: [] | [bigint];
}): {
    minValue?: bigint;
    required: boolean;
    maxLength?: bigint;
    maxValue?: bigint;
    minLength?: bigint;
} {
    return {
        minValue: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.minValue)),
        required: value.required,
        maxLength: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxLength)),
        maxValue: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.maxValue)),
        minLength: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.minLength))
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _TaskAction;
    user: Principal;
    taskId: string;
    timestamp: bigint;
    details: string;
}): {
    action: TaskAction;
    user: Principal;
    taskId: string;
    timestamp: bigint;
    details: string;
} {
    return {
        action: from_candid_TaskAction_n69(_uploadFile, _downloadFile, value.action),
        user: value.user,
        taskId: value.taskId,
        timestamp: value.timestamp,
        details: value.details
    };
}
async function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
} | {
    file: _ExternalBlob;
} | {
    text: string;
} | {
    singleChoice: string;
} | {
    number: bigint;
} | {
    multipleChoices: Array<string>;
} | {
    dateTime: bigint;
}): Promise<{
    __kind__: "date";
    date: bigint;
} | {
    __kind__: "file";
    file: ExternalBlob;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "singleChoice";
    singleChoice: string;
} | {
    __kind__: "number";
    number: bigint;
} | {
    __kind__: "multipleChoices";
    multipleChoices: Array<string>;
} | {
    __kind__: "dateTime";
    dateTime: bigint;
}> {
    return "date" in value ? {
        __kind__: "date",
        date: value.date
    } : "file" in value ? {
        __kind__: "file",
        file: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.file)
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : "singleChoice" in value ? {
        __kind__: "singleChoice",
        singleChoice: value.singleChoice
    } : "number" in value ? {
        __kind__: "number",
        number: value.number
    } : "multipleChoices" in value ? {
        __kind__: "multipleChoices",
        multipleChoices: value.multipleChoices
    } : "dateTime" in value ? {
        __kind__: "dateTime",
        dateTime: value.dateTime
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
} | {
    department: string;
}): {
    __kind__: "user";
    user: Principal;
} | {
    __kind__: "department";
    department: string;
} {
    return "user" in value ? {
        __kind__: "user",
        user: value.user
    } : "department" in value ? {
        __kind__: "department",
        department: value.department
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: null;
} | {
    multiSelect: null;
} | {
    fileUpload: null;
} | {
    multiLine: null;
} | {
    number: null;
} | {
    singleLine: null;
} | {
    dateTime: null;
} | {
    dropdown: null;
}): FieldType {
    return "date" in value ? FieldType.date : "multiSelect" in value ? FieldType.multiSelect : "fileUpload" in value ? FieldType.fileUpload : "multiLine" in value ? FieldType.multiLine : "number" in value ? FieldType.number : "singleLine" in value ? FieldType.singleLine : "dateTime" in value ? FieldType.dateTime : "dropdown" in value ? FieldType.dropdown : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    created: null;
} | {
    escalated: null;
} | {
    completed: null;
} | {
    formSubmitted: null;
} | {
    pickedUp: null;
} | {
    statusChanged: null;
} | {
    reassigned: null;
}): TaskAction {
    return "assigned" in value ? TaskAction.assigned : "created" in value ? TaskAction.created : "escalated" in value ? TaskAction.escalated : "completed" in value ? TaskAction.completed : "formSubmitted" in value ? TaskAction.formSubmitted : "pickedUp" in value ? TaskAction.pickedUp : "statusChanged" in value ? TaskAction.statusChanged : "reassigned" in value ? TaskAction.reassigned : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DynamicFormInput>): Promise<Array<DynamicFormInput>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DynamicFormInput_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormFieldInput>): Promise<Array<FormFieldInput>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FormFieldInput_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormField>): Array<FormField> {
    return value.map((x)=>from_candid_FormField_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormDefinition>): Array<FormDefinition> {
    return value.map((x)=>from_candid_FormDefinition_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskAuditEntry>): Array<TaskAuditEntry> {
    return value.map((x)=>from_candid_TaskAuditEntry_n67(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): _AssignmentType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_DynamicFormInput_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DynamicFormInput): Promise<_DynamicFormInput> {
    return await to_candid_record_n75(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FieldType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldType): _FieldType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_FieldValue_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldValue): Promise<_FieldValue> {
    return await to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_FormDefinition_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormDefinition): _FormDefinition {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_FormFieldInput_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormFieldInput): Promise<_FormFieldInput> {
    return await to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_FormField_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormField): _FormField {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ValidationRules_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ValidationRules): _ValidationRules {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: bigint;
    creator: Principal;
    name: string;
    lastUpdated: bigint;
    version: bigint;
    fields: Array<FormField>;
}): {
    id: string;
    created: bigint;
    creator: Principal;
    name: string;
    lastUpdated: bigint;
    version: bigint;
    fields: Array<_FormField>;
} {
    return {
        id: value.id,
        created: value.created,
        creator: value.creator,
        name: value.name,
        lastUpdated: value.lastUpdated,
        version: value.version,
        fields: to_candid_vec_n14(_uploadFile, _downloadFile, value.fields)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    masterListRef?: string;
    fieldLabel: string;
    validations?: ValidationRules;
    options?: Array<FormFieldOption>;
    fieldType: FieldType;
}): {
    id: string;
    masterListRef: [] | [string];
    fieldLabel: string;
    validations: [] | [_ValidationRules];
    options: [] | [Array<_FormFieldOption>];
    fieldType: _FieldType;
} {
    return {
        id: value.id,
        masterListRef: value.masterListRef ? candid_some(value.masterListRef) : candid_none(),
        fieldLabel: value.fieldLabel,
        validations: value.validations ? candid_some(to_candid_ValidationRules_n17(_uploadFile, _downloadFile, value.validations)) : candid_none(),
        options: value.options ? candid_some(value.options) : candid_none(),
        fieldType: to_candid_FieldType_n19(_uploadFile, _downloadFile, value.fieldType)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minValue?: bigint;
    required: boolean;
    maxLength?: bigint;
    maxValue?: bigint;
    minLength?: bigint;
}): {
    minValue: [] | [bigint];
    required: boolean;
    maxLength: [] | [bigint];
    maxValue: [] | [bigint];
    minLength: [] | [bigint];
} {
    return {
        minValue: value.minValue ? candid_some(value.minValue) : candid_none(),
        required: value.required,
        maxLength: value.maxLength ? candid_some(value.maxLength) : candid_none(),
        maxValue: value.maxValue ? candid_some(value.maxValue) : candid_none(),
        minLength: value.minLength ? candid_some(value.minLength) : candid_none()
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    completionDate?: bigint;
    assignment?: AssignmentType;
    owner: Principal;
    attachedForms: Array<TaskFormAttachment>;
    createdDate: bigint;
    dueDate: bigint;
    taskType: string;
    priority: string;
}): {
    id: string;
    status: string;
    completionDate: [] | [bigint];
    assignment: [] | [_AssignmentType];
    owner: Principal;
    attachedForms: Array<_TaskFormAttachment>;
    createdDate: bigint;
    dueDate: bigint;
    taskType: string;
    priority: string;
} {
    return {
        id: value.id,
        status: value.status,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        assignment: value.assignment ? candid_some(to_candid_AssignmentType_n10(_uploadFile, _downloadFile, value.assignment)) : candid_none(),
        owner: value.owner,
        attachedForms: value.attachedForms,
        createdDate: value.createdDate,
        dueDate: value.dueDate,
        taskType: value.taskType,
        priority: value.priority
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    department?: string;
}): {
    name: string;
    email: [] | [string];
    department: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none()
    };
}
async function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    data: Array<FormFieldInput>;
    submittedAt: bigint;
    submittedBy: Principal;
    version: bigint;
    formId: string;
}): Promise<{
    data: Array<_FormFieldInput>;
    submittedAt: bigint;
    submittedBy: Principal;
    version: bigint;
    formId: string;
}> {
    return {
        data: await to_candid_vec_n76(_uploadFile, _downloadFile, value.data),
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        version: value.version,
        formId: value.formId
    };
}
async function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: FieldValue;
    fieldId: string;
}): Promise<{
    value: _FieldValue;
    fieldId: string;
}> {
    return {
        value: await to_candid_FieldValue_n79(_uploadFile, _downloadFile, value.value),
        fieldId: value.fieldId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "user";
    user: Principal;
} | {
    __kind__: "department";
    department: string;
}): {
    user: Principal;
} | {
    department: string;
} {
    return value.__kind__ === "user" ? {
        user: value.user
    } : value.__kind__ === "department" ? {
        department: value.department
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldType): {
    date: null;
} | {
    multiSelect: null;
} | {
    fileUpload: null;
} | {
    multiLine: null;
} | {
    number: null;
} | {
    singleLine: null;
} | {
    dateTime: null;
} | {
    dropdown: null;
} {
    return value == FieldType.date ? {
        date: null
    } : value == FieldType.multiSelect ? {
        multiSelect: null
    } : value == FieldType.fileUpload ? {
        fileUpload: null
    } : value == FieldType.multiLine ? {
        multiLine: null
    } : value == FieldType.number ? {
        number_: null
    } : value == FieldType.singleLine ? {
        singleLine: null
    } : value == FieldType.dateTime ? {
        dateTime: null
    } : value == FieldType.dropdown ? {
        dropdown: null
    } : value;
}
async function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "date";
    date: bigint;
} | {
    __kind__: "file";
    file: ExternalBlob;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "singleChoice";
    singleChoice: string;
} | {
    __kind__: "number";
    number: bigint;
} | {
    __kind__: "multipleChoices";
    multipleChoices: Array<string>;
} | {
    __kind__: "dateTime";
    dateTime: bigint;
}): Promise<{
    date: bigint;
} | {
    file: _ExternalBlob;
} | {
    text: string;
} | {
    singleChoice: string;
} | {
    number: bigint;
} | {
    multipleChoices: Array<string>;
} | {
    dateTime: bigint;
}> {
    return value.__kind__ === "date" ? {
        date: value.date
    } : value.__kind__ === "file" ? {
        file: await to_candid_ExternalBlob_n81(_uploadFile, _downloadFile, value.file)
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value.__kind__ === "singleChoice" ? {
        singleChoice: value.singleChoice
    } : value.__kind__ === "number" ? {
        number: value.number
    } : value.__kind__ === "multipleChoices" ? {
        multipleChoices: value.multipleChoices
    } : value.__kind__ === "dateTime" ? {
        dateTime: value.dateTime
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FormField>): Array<_FormField> {
    return value.map((x)=>to_candid_FormField_n15(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FormFieldInput>): Promise<Array<_FormFieldInput>> {
    return await Promise.all(value.map(async (x)=>await to_candid_FormFieldInput_n77(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
